; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = debug

[env]
platform = espressif8266
board = d1_mini
framework = arduino
lib_extra_dirs = ~/Desktop/Code/Arduino/libraries
monitor_speed = 115200
platform_packages = 
	toolchain-xtensa@file://C:/Users/Saqib/Documents/Collection/SoftwareDevelopment/Esp8266/toolchain-xtensa
	framework-arduinoespressif8266@file://C:/Users/Saqib/Documents/Collection/SoftwareDevelopment/Esp8266/deauther-esp8266
upload_speed = 921600

[env:release]
build_type = release

[env:debug]
build_type = debug
build_flags = -DENABLE_DEBUG -DDEBUG_PORT=Serial -DDEBUG_BAUD=115200 -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_CORE -DDEBUG_ESP_WIFI
