#pragma once

/* CHANNEL BOUNDS */
#define MAX_CHANNEL ((byte)14)
#define MIN_CHANNEL ((byte)1)
#define CH_MASK_LEAST (MIN_CHANNEL - 1)
#define CH_MASK_MOST (MAX_CHANNEL - 1)

/* LISTS */
#define MAX_ACCESS_POINTS 50
#define MAX_NETWORKS MAX_ACCESS_POINTS
#define MAX_STATIONS 100

/* WIFIMANAGER AP CONFIG */
#define DEFAULT_IP IPAddress(192, 168, 4, 1)

/* DEFAULT NETWORK PROPERTIES */
#define HIDDEN_NETWORK_MARKER PSTR("<HIDDEN>")
#define DEFAULT_NETWORK_CHANNEL 1

/* CHANNEL HOPPING ATTRIBUTES */
#define CHANNEL_HOP_INTERVAL_DEFAULT 284
#define CHANNEL_HOP_INTERVAL_MIN 50
// #define CHANNEL_HOP_INTERVAL_MAX NULL

/* MISC IDENTIFIERS */
#define SWITCH_ON true
#define SWITCH_OFF false

/* SCANNING CONTROLLERS */

#define QUICK_SCAN 0
#define DEFAULT_SCAN_TIMEOUT 15000
#define MAX_SCAN_TIMEOUT (5 * 1000 * 60)